# Generated by Django 5.2 on 2025-05-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savecontact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecontact',
            name='s_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
