# Generated by Django 5.2 on 2025-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indexCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_img', models.CharField(max_length=400)),
                ('ic_strikeprice', models.CharField(max_length=200)),
                ('ic_price', models.CharField(max_length=200)),
                ('ic_title', models.CharField(max_length=200)),
                ('ic_sp1', models.CharField(max_length=200)),
                ('ic_sp2', models.CharField(max_length=200)),
                ('ic_sp3', models.CharField(max_length=200)),
            ],
        ),
    ]
