# Generated by Django 5.2 on 2025-04-28 13:42

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_img', models.CharField(max_length=200)),
                ('testimonial_name', models.CharField(max_length=200)),
                ('testimonial_position', models.CharField(max_length=200)),
                ('testimonial_rating', models.CharField(max_length=200)),
                ('testimonial_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
