# Generated by Django 5.2 on 2025-04-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('team_field', models.CharField(max_length=20)),
                ('team_desc', models.TextField()),
            ],
        ),
    ]
