# Generated by Django 5.2 on 2025-04-28 03:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_team_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
