# Generated by Django 5.2 on 2025-04-28 08:56

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs_img', models.CharField(max_length=200)),
                ('blogs_title', models.CharField(max_length=200)),
                ('blogs_area', models.CharField(max_length=200)),
                ('blogs_desc', tinymce.models.HTMLField()),
                ('blogs_name', models.CharField(max_length=200)),
                ('blogs_date', models.CharField(max_length=200)),
            ],
        ),
    ]
