# Generated by Django 5.2 on 2025-04-28 04:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.CharField(max_length=200)),
                ('slider_title', models.CharField(max_length=200)),
                ('slider_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
