# Generated by Django 5.2 on 2025-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indexPurifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_off', models.CharField(max_length=20)),
                ('ip_img', models.CharField(max_length=400)),
                ('ip_stock', models.CharField(max_length=50)),
                ('ip_title', models.CharField(max_length=200)),
                ('ip_rating', models.CharField(max_length=200)),
                ('ip_price', models.CharField(max_length=200)),
                ('ip_strikeprice', models.CharField(max_length=200)),
                ('ip_save', models.CharField(max_length=200)),
                ('ip_sp1', models.CharField(max_length=200)),
                ('ip_sp2', models.CharField(max_length=200)),
                ('ip_sp3', models.CharField(max_length=200)),
            ],
        ),
    ]
