# Generated by Django 5.2 on 2025-04-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_banner_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_text',
            field=models.CharField(max_length=200),
        ),
    ]
