# Generated by Django 5.2 on 2025-04-29 06:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_blog_img', models.CharField(max_length=200)),
                ('main_blog_news', models.CharField(max_length=200)),
                ('main_blog_title', models.CharField(max_length=200)),
                ('main_blog_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
